-- =========================================================================
-- SCRIPT DE BASE DE DATOS SUPABASE (PostgreSQL)
-- Plataforma: Espacio Seguro
-- Compatible con: GitHub Pages y Servidor Web
-- =========================================================================
-- INSTRUCCIONES:
-- 1. Abre tu panel de Supabase (https://app.supabase.com)
-- 2. Entra a tu proyecto -> Menú lateral "SQL Editor" -> "New query"
-- 3. Pega TODO este contenido y presiona "Run" (o Ctrl + Enter)
-- =========================================================================

-- 1. Crear tabla de experiencias
CREATE TABLE IF NOT EXISTS public.experiencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    tipo_acoso VARCHAR(50) NOT NULL CHECK (tipo_acoso IN ('escolar', 'laboral', 'cibernetico', 'otro')),
    relato TEXT NOT NULL,
    fecha DATE NOT NULL,
    anonimo BOOLEAN NOT NULL DEFAULT true,
    alias VARCHAR(100) DEFAULT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'publicado', 'rechazado')),
    apoyos_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Crear índices de rendimiento
CREATE INDEX IF NOT EXISTS idx_experiencias_estado_created ON public.experiencias (estado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_experiencias_tipo ON public.experiencias (tipo_acoso);

-- 3. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.experiencias ENABLE ROW LEVEL SECURITY;

-- 4. Limpiar políticas anteriores
DROP POLICY IF EXISTS "Lectura pública de experiencias publicadas" ON public.experiencias;
DROP POLICY IF EXISTS "Inserción pública con estado pendiente" ON public.experiencias;
DROP POLICY IF EXISTS "Permitir actualizar contador de apoyos" ON public.experiencias;
DROP POLICY IF EXISTS "Permitir moderacion para administradores" ON public.experiencias;
DROP POLICY IF EXISTS "anon_select_publicado" ON public.experiencias;
DROP POLICY IF EXISTS "anon_insert_pendiente" ON public.experiencias;
DROP POLICY IF EXISTS "anon_update_apoyos" ON public.experiencias;
DROP POLICY IF EXISTS "all_access" ON public.experiencias;
DROP POLICY IF EXISTS "service_access" ON public.experiencias;
DROP POLICY IF EXISTS "public_select" ON public.experiencias;
DROP POLICY IF EXISTS "public_insert" ON public.experiencias;
DROP POLICY IF EXISTS "public_update" ON public.experiencias;
DROP POLICY IF EXISTS "public_delete" ON public.experiencias;

-- 5. POLÍTICAS RLS PARA GITHUB PAGES / APLICACIÓN ESTÁTICA
-- Permite lectura de registros (el feed filtra por 'publicado' y el panel admin por estado)
CREATE POLICY "public_select"
ON public.experiencias FOR SELECT
TO anon, authenticated, service_role
USING (true);

-- Permite inserción pública de testimonios
CREATE POLICY "public_insert"
ON public.experiencias FOR INSERT
TO anon, authenticated, service_role
WITH CHECK (true);

-- Permite actualizar estado (aprobar/rechazar) y sumar apoyos
CREATE POLICY "public_update"
ON public.experiencias FOR UPDATE
TO anon, authenticated, service_role
USING (true)
WITH CHECK (true);

-- Permite eliminar registros desde la moderación
CREATE POLICY "public_delete"
ON public.experiencias FOR DELETE
TO anon, authenticated, service_role
USING (true);

-- 6. Insertar datos iniciales de ejemplo (solo si la tabla está vacía)
INSERT INTO public.experiencias (titulo, tipo_acoso, relato, fecha, anonimo, alias, estado, apoyos_count, created_at)
SELECT * FROM (VALUES
(
    'Aprender a poner límites en la preparatoria',
    'escolar',
    'Durante mi primer año de preparatoria, un grupo de compañeros comenzó a burlarse de mi forma de vestir. Al principio guardé silencio por miedo, pero el estrés empezó a afectar mi salud. Decidí contárselo a una profesora de confianza y a mi madre. Juntas acudimos con la dirección escolar. Aunque tomó tiempo, el apoyo me devolvió la tranquilidad. Pedir ayuda no te hace débil; es el primer paso para protegerte.',
    '2024-03-15'::DATE, true, NULL::VARCHAR, 'publicado', 14, NOW() - INTERVAL '3 days'
),
(
    'Superando el ciberacoso y recuperando mi espacio digital',
    'cibernetico',
    'Crearon un perfil falso en redes sociales usando mis fotos para difundir rumores. Guardé capturas de pantalla de todo como evidencia y reporté la cuenta en la plataforma. Además, hablé con la Línea de la Vida para recibir contención emocional. Hoy sé que lo que otros digan en una pantalla no define quién soy.',
    '2024-05-20'::DATE, false, 'Camila R.', 'publicado', 28, NOW() - INTERVAL '2 days'
),
(
    'Hacer frente a la intimidación y sobrecarga laboral',
    'laboral',
    'En mi trabajo anterior, un supervisor utilizaba comentarios despectivos y me excluía de reuniones importantes de manera deliberada. Empecé a registrar cada incidente con fecha, hora y correos de respaldo. Cuando la situación fue insostenible, presenté el reporte ante Recursos Humanos con las pruebas organizadas. No normalices ningún maltrato.',
    '2024-08-10'::DATE, true, NULL::VARCHAR, 'publicado', 9, NOW() - INTERVAL '1 day'
)
) AS v(titulo, tipo_acoso, relato, fecha, anonimo, alias, estado, apoyos_count, created_at)
WHERE NOT EXISTS (SELECT 1 FROM public.experiencias LIMIT 1);
